In [0]:
import torch

In [0]:
x = torch.Tensor([2,3])

In [0]:
y = torch.Tensor([5,1])

In [7]:
print(x*y)

tensor([10.,  3.])


In [14]:
torch.Size([2,5])

torch.Size([2, 5])

In [15]:
y.view[1,10]

TypeError: ignored

In [16]:
x = torch.zeros([2,5])
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [18]:
print(x.shape)


torch.Size([2, 5])


In [22]:
y = torch.rand([2,5])
print(y)

tensor([[0.3007, 0.1383, 0.5695, 0.8799, 0.2669],
        [0.3174, 0.7315, 0.7474, 0.7176, 0.0674]])


In [0]:
y.view([1,10])